client_config_backend: settings
client_config:
  client_id: "669041100363-lcb9vmlkf2s3646tpajb787dsbgs5bgd.apps.googleusercontent.com"
  client_secret: "i7XuDmkVlQ3sREoTSbhT4wvY"

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install